services:
  web:
    restart: unless-stopped
    build: .
    ports:
      - "1234:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/db
    volumes:
      - .:/app
      - /app/node_modules
  
  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: